version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/code
    # command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    # restart: always
    depends_on:
      - ollama
    networks:
      - network-scope

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    networks:
      - network-scope

networks:
  network-scope:
      external: false